module.exports = {
  COMMAND_MONSTER_LIST: 'COMMAND_MONSTER_LIST',
  COMMAND_PLAYER_INIT: 'COMMAND_PLAYER_INIT',
  COMMAND_MONSTER_CATCH_WATER: 'COMMAND_MONSTER_CATCH_WATER',
  COMMAND_MONSTER_CATCH_GRASS: 'COMMAND_MONSTER_CATCH_GRASS',
  COMMAND_MONSTER_CATCH_SAT: 'COMMAND_MONSTER_CATCH_SAT',
  COMMAND_MONSTER_OPTIONS: 'COMMAND_MONSTER_OPTIONS',

  COMMAND_MONSTER_PK_WIN: 'COMMAND_MONSTER_PK_WIN',
  COMMAND_MONSTER_PK_FAIL: 'COMMAND_MONSTER_PK_FAIL',

  MONSTER_PIKACHU: 'MONSTER_PIKACHU',
  MONSTER_PSYDUCK: 'MONSTER_PSYDUCK',
  MONSTER_DOGE: 'MONSTER_DOGE',
  SPECIAL_BEAR: 'SPECIAL_BEAR',
};
